import type { Metadata } from 'next';
import './styles.scss'

import GoogleAnalytics from '@/app/components/GAnalytics';
import CookieBanner from '@/app/components/CookieBanner';
import Header from '@/app/components/layout/Header';
import Footer from '@/app/components/layout/Footer';

export const metadata: Metadata = {
  title: 'AIDABE',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <GoogleAnalytics GA_MEASUREMENT_ID={process.env.GA_MEASUREMENT_ID || ""} />
      <body>
        <Header />
        {children}
        <CookieBanner />
        <Footer />
      </body>
    </html>
  )
}
